---
name: first-network-componentsupplier
version: 1.0.0
client:
  organization: ComponentSupplier
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  ComponentSupplier:
    mspid: ComponentSupplierMSP
    peers:
    - peer0.componentsupplier.ibo.com
    - peer1.componentsupplier.ibo.com
    certificateAuthorities:
    - ca.componentsupplier.ibo.com
peers:
  peer0.componentsupplier.ibo.com:
    url: grpcs://localhost:9051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICfjCCAiSgAwIBAgIRAOWQfZQ27cBhWxWf0BlEGkwwCgYIKoZIzj0EAwIwgYgx
        CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4g
        RnJhbmNpc2NvMSIwIAYDVQQKExljb21wb25lbnRzdXBwbGllci5pYm8uY29tMSgw
        JgYDVQQDEx90bHNjYS5jb21wb25lbnRzdXBwbGllci5pYm8uY29tMB4XDTIwMDgy
        MTIxMDMwMFoXDTMwMDgxOTIxMDMwMFowgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQI
        EwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMSIwIAYDVQQKExlj
        b21wb25lbnRzdXBwbGllci5pYm8uY29tMSgwJgYDVQQDEx90bHNjYS5jb21wb25l
        bnRzdXBwbGllci5pYm8uY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEGF5O
        a6opjhlo340vuNEHhwFtJZ50+hcUoSjlq6P5GseOsqeFCttSdjtHj5aiDOXjakrS
        C3rwpMIok2dzx5I9wqNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsG
        AQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCCx58ve
        XlbkzBlPow1I6lhXnh23ARGLPddhBy4JD/jwWTAKBggqhkjOPQQDAgNIADBFAiBk
        I+DgG7ngSDIouqKFxs8PSvdwRIuAyC5UdHWBE49+dAIhAPrFaOY9R6X+HK+tAUrQ
        w0NWKXAgetuXg2wR8xp5DFpg
        -----END CERTIFICATE-----
        
        
    grpcOptions:
      ssl-target-name-override: peer0.componentsupplier.ibo.com
      hostnameOverride: peer0.componentsupplier.ibo.com
  peer1.componentsupplier.ibo.com:
    url: grpcs://localhost:9055
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICfjCCAiSgAwIBAgIRAOWQfZQ27cBhWxWf0BlEGkwwCgYIKoZIzj0EAwIwgYgx
        CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4g
        RnJhbmNpc2NvMSIwIAYDVQQKExljb21wb25lbnRzdXBwbGllci5pYm8uY29tMSgw
        JgYDVQQDEx90bHNjYS5jb21wb25lbnRzdXBwbGllci5pYm8uY29tMB4XDTIwMDgy
        MTIxMDMwMFoXDTMwMDgxOTIxMDMwMFowgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQI
        EwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMSIwIAYDVQQKExlj
        b21wb25lbnRzdXBwbGllci5pYm8uY29tMSgwJgYDVQQDEx90bHNjYS5jb21wb25l
        bnRzdXBwbGllci5pYm8uY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEGF5O
        a6opjhlo340vuNEHhwFtJZ50+hcUoSjlq6P5GseOsqeFCttSdjtHj5aiDOXjakrS
        C3rwpMIok2dzx5I9wqNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsG
        AQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCCx58ve
        XlbkzBlPow1I6lhXnh23ARGLPddhBy4JD/jwWTAKBggqhkjOPQQDAgNIADBFAiBk
        I+DgG7ngSDIouqKFxs8PSvdwRIuAyC5UdHWBE49+dAIhAPrFaOY9R6X+HK+tAUrQ
        w0NWKXAgetuXg2wR8xp5DFpg
        -----END CERTIFICATE-----
        
        
    grpcOptions:
      ssl-target-name-override: peer1.componentsupplier.ibo.com
      hostnameOverride: peer1.componentsupplier.ibo.com
certificateAuthorities:
  ca.componentsupplier.ibo.com:
    url: https://localhost:9054
    caName: ca-componentsupplier
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICfjCCAiOgAwIBAgIQF8CzmXdSOFqxHJVkZXv6PzAKBggqhkjOPQQDAjCBiDEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xIjAgBgNVBAoTGWNvbXBvbmVudHN1cHBsaWVyLmliby5jb20xKDAm
        BgNVBAMTH3Rsc2NhLmNvbXBvbmVudHN1cHBsaWVyLmliby5jb20wHhcNMjAwODI0
        MjAzMzAwWhcNMzAwODIyMjAzMzAwWjCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgT
        CkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xIjAgBgNVBAoTGWNv
        bXBvbmVudHN1cHBsaWVyLmliby5jb20xKDAmBgNVBAMTH3Rsc2NhLmNvbXBvbmVu
        dHN1cHBsaWVyLmliby5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQsVQzv
        VLKGIvUngwtc8B6J39A+jnjsEg2qtkLnxFkHFp4A53uPGMH0bMgSfHbQSmxT8k9q
        F4z5aTi/J/9ovtAHo20wazAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYB
        BQUHAwIGCCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0OBCIEIJskWK3a
        BOjBeXYQd9rIzlP7g6GXEFZKbc699Jei/cw1MAoGCCqGSM49BAMCA0kAMEYCIQD3
        1qA6y4EiN4D1XFg9Yb/y1J+8g8tBq0ZYBVuycYk9JQIhAKQ5Rs4uyHuH9+ZIp/J/
        SpdCT0/lX52ECkpC76rdmxLp
        -----END CERTIFICATE-----
               
            
        
    httpOptions:
      verify: false
