---
name: first-network-manufacturer
version: 1.0.0
client:
  organization: Manufacturer
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Manufacturer:
    mspid: ManufacturerMSP
    peers:
    - peer0.manufacturer.ibo.com
    - peer1.manufacturer.ibo.com
    certificateAuthorities:
    - ca.manufacturer.ibo.com
peers:
  peer0.manufacturer.ibo.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICaTCCAg6gAwIBAgIRAIgGiREl97nHLqqDvyQmz00wCgYIKoZIzj0EAwIwfjEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xHTAbBgNVBAoTFG1hbnVmYWN0dXJlci5pYm8uY29tMSMwIQYDVQQD
        Exp0bHNjYS5tYW51ZmFjdHVyZXIuaWJvLmNvbTAeFw0yMDA4MjEyMTAzMDBaFw0z
        MDA4MTkyMTAzMDBaMH4xCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlh
        MRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMR0wGwYDVQQKExRtYW51ZmFjdHVyZXIu
        aWJvLmNvbTEjMCEGA1UEAxMadGxzY2EubWFudWZhY3R1cmVyLmliby5jb20wWTAT
        BgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ5CZ2+k6stl8X5nM/h86JMcTl6sbSDGgxz
        BMuzowiJrpS2jj5s51NHgoyH0Ol5W1Z74+IjbspwJozD1MsJ/lAfo20wazAOBgNV
        HQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMA8GA1Ud
        EwEB/wQFMAMBAf8wKQYDVR0OBCIEIFoWuyzQpriZCd5ijCzlzvLRCMrZO9zeaATL
        n5WlM5WKMAoGCCqGSM49BAMCA0kAMEYCIQDupxX6iSkiwzib05t8HiVRw6w23SgP
        SkjoKtA7f1o3cAIhAIJlfbwWV0c2lB8XC1HoK/Fjhtqhdn8ceC3M5E0MfEdB
        -----END CERTIFICATE-----
        
        
    grpcOptions:
      ssl-target-name-override: peer0.manufacturer.ibo.com
      hostnameOverride: peer0.manufacturer.ibo.com
  peer1.manufacturer.ibo.com:
    url: grpcs://localhost:7055
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICaTCCAg6gAwIBAgIRAIgGiREl97nHLqqDvyQmz00wCgYIKoZIzj0EAwIwfjEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xHTAbBgNVBAoTFG1hbnVmYWN0dXJlci5pYm8uY29tMSMwIQYDVQQD
        Exp0bHNjYS5tYW51ZmFjdHVyZXIuaWJvLmNvbTAeFw0yMDA4MjEyMTAzMDBaFw0z
        MDA4MTkyMTAzMDBaMH4xCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlh
        MRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMR0wGwYDVQQKExRtYW51ZmFjdHVyZXIu
        aWJvLmNvbTEjMCEGA1UEAxMadGxzY2EubWFudWZhY3R1cmVyLmliby5jb20wWTAT
        BgcqhkjOPQIBBggqhkjOPQMBBwNCAAQ5CZ2+k6stl8X5nM/h86JMcTl6sbSDGgxz
        BMuzowiJrpS2jj5s51NHgoyH0Ol5W1Z74+IjbspwJozD1MsJ/lAfo20wazAOBgNV
        HQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMA8GA1Ud
        EwEB/wQFMAMBAf8wKQYDVR0OBCIEIFoWuyzQpriZCd5ijCzlzvLRCMrZO9zeaATL
        n5WlM5WKMAoGCCqGSM49BAMCA0kAMEYCIQDupxX6iSkiwzib05t8HiVRw6w23SgP
        SkjoKtA7f1o3cAIhAIJlfbwWV0c2lB8XC1HoK/Fjhtqhdn8ceC3M5E0MfEdB
        -----END CERTIFICATE-----
        
        
    grpcOptions:
      ssl-target-name-override: peer1.manufacturer.ibo.com
      hostnameOverride: peer1.manufacturer.ibo.com
certificateAuthorities:
  ca.manufacturer.ibo.com:
    url: https://localhost:7054
    caName: ca.manufacturer.ibo.com
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICaDCCAg6gAwIBAgIRAKUMZK2hOR8b7D+FBGLM3uEwCgYIKoZIzj0EAwIwfjEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xHTAbBgNVBAoTFG1hbnVmYWN0dXJlci5pYm8uY29tMSMwIQYDVQQD
        Exp0bHNjYS5tYW51ZmFjdHVyZXIuaWJvLmNvbTAeFw0yMDA4MjQyMDMzMDBaFw0z
        MDA4MjIyMDMzMDBaMH4xCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlh
        MRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMR0wGwYDVQQKExRtYW51ZmFjdHVyZXIu
        aWJvLmNvbTEjMCEGA1UEAxMadGxzY2EubWFudWZhY3R1cmVyLmliby5jb20wWTAT
        BgcqhkjOPQIBBggqhkjOPQMBBwNCAAR4QAfxTKf5MOqyX/GyfrhdYsuTg5AevP63
        izZK+L3mC1Knr/1gx8FzXBjfw7adjlscGwvEwFh/VK2Z9Dqa87Gho20wazAOBgNV
        HQ8BAf8EBAMCAaYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMA8GA1Ud
        EwEB/wQFMAMBAf8wKQYDVR0OBCIEIF6xVBABRhGZxSJPMYU/2JRpbaU+ZYI1DSmY
        Y7Mw0UGkMAoGCCqGSM49BAMCA0gAMEUCIF4iybHEQA66zRd0H9rBv0VSpSdbH4Uy
        LYLqVsLGeNLhAiEA64XKIwJqok4FekIx9fHzfrXg9xzuulf5oPDcR4BGCjM=
        -----END CERTIFICATE-----
        
    
    httpOptions:
      verify: false
