---
name: first-network-customer
version: 1.0.0
client:
  organization: Customer
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Customer:
    mspid: CustomerMSP
    peers:
    - peer0.customer.ibo.com
    - peer1.customer.ibo.com
    certificateAuthorities:
    - ca.customer.ibo.com
peers:
  peer0.customer.ibo.com:
    url: grpcs://localhost:6051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWDCCAf6gAwIBAgIRAIZvI0gk8kEXDkk+l7tBcKAwCgYIKoZIzj0EAwIwdjEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xGTAXBgNVBAoTEGN1c3RvbWVyLmliby5jb20xHzAdBgNVBAMTFnRs
        c2NhLmN1c3RvbWVyLmliby5jb20wHhcNMjAwODI0MjAzMzAwWhcNMzAwODIyMjAz
        MzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQY3VzdG9tZXIuaWJvLmNvbTEfMB0G
        A1UEAxMWdGxzY2EuY3VzdG9tZXIuaWJvLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
        AwEHA0IABFqWD48BYDnqVY9+mot8jb7icIxaBFpRxMtzZglRSUBtdNw6u4pLCDwC
        vWAjq39Nf/Rg7rAGU7UUd47tL8gwCz2jbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
        HQ4EIgQgYhlfhBhXekxh1FGwQ8Bc+8AnonKh5I1EsepybdBdO90wCgYIKoZIzj0E
        AwIDSAAwRQIgEv22EfyUVMwCG3OBjpXZ/WICcmTMesVcThNQpQ218HcCIQCzlk/3
        3+UDhvS66aS3PxL5eQS4E/MtN9UOVTKHeuN7wQ==
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer0.customer.ibo.com
      hostnameOverride: peer0.customer.ibo.com
  peer1.customer.ibo.com:
    url: grpcs://localhost:6055
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWDCCAf6gAwIBAgIRAIZvI0gk8kEXDkk+l7tBcKAwCgYIKoZIzj0EAwIwdjEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xGTAXBgNVBAoTEGN1c3RvbWVyLmliby5jb20xHzAdBgNVBAMTFnRs
        c2NhLmN1c3RvbWVyLmliby5jb20wHhcNMjAwODI0MjAzMzAwWhcNMzAwODIyMjAz
        MzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQY3VzdG9tZXIuaWJvLmNvbTEfMB0G
        A1UEAxMWdGxzY2EuY3VzdG9tZXIuaWJvLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
        AwEHA0IABFqWD48BYDnqVY9+mot8jb7icIxaBFpRxMtzZglRSUBtdNw6u4pLCDwC
        vWAjq39Nf/Rg7rAGU7UUd47tL8gwCz2jbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
        HQ4EIgQgYhlfhBhXekxh1FGwQ8Bc+8AnonKh5I1EsepybdBdO90wCgYIKoZIzj0E
        AwIDSAAwRQIgEv22EfyUVMwCG3OBjpXZ/WICcmTMesVcThNQpQ218HcCIQCzlk/3
        3+UDhvS66aS3PxL5eQS4E/MtN9UOVTKHeuN7wQ==
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer1.customer.ibo.com
      hostnameOverride: peer1.customer.ibo.com
certificateAuthorities:
  ca.customer.ibo.com:
    url: https://localhost:6054
    caName: ca.customer.ibo.com
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWDCCAf6gAwIBAgIRAIZvI0gk8kEXDkk+l7tBcKAwCgYIKoZIzj0EAwIwdjEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xGTAXBgNVBAoTEGN1c3RvbWVyLmliby5jb20xHzAdBgNVBAMTFnRs
        c2NhLmN1c3RvbWVyLmliby5jb20wHhcNMjAwODI0MjAzMzAwWhcNMzAwODIyMjAz
        MzAwWjB2MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UE
        BxMNU2FuIEZyYW5jaXNjbzEZMBcGA1UEChMQY3VzdG9tZXIuaWJvLmNvbTEfMB0G
        A1UEAxMWdGxzY2EuY3VzdG9tZXIuaWJvLmNvbTBZMBMGByqGSM49AgEGCCqGSM49
        AwEHA0IABFqWD48BYDnqVY9+mot8jb7icIxaBFpRxMtzZglRSUBtdNw6u4pLCDwC
        vWAjq39Nf/Rg7rAGU7UUd47tL8gwCz2jbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNV
        HSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNV
        HQ4EIgQgYhlfhBhXekxh1FGwQ8Bc+8AnonKh5I1EsepybdBdO90wCgYIKoZIzj0E
        AwIDSAAwRQIgEv22EfyUVMwCG3OBjpXZ/WICcmTMesVcThNQpQ218HcCIQCzlk/3
        3+UDhvS66aS3PxL5eQS4E/MtN9UOVTKHeuN7wQ==
        -----END CERTIFICATE-----
    httpOptions:
      verify: false
