---
name: first-network-rawmaterialsupplier
version: 1.0.0
client:
  organization: RawMaterialSupplier
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  RawMaterialSupplier:
    mspid: RawMaterialSupplierMSP
    peers:
    - peer0.rawmaterialsupplier.ibo.com
    - peer1.rawmaterialsupplier.ibo.com
    certificateAuthorities:
    - ca.rawmaterialsupplier.ibo.com
peers:
  peer0.rawmaterialsupplier.ibo.com:
    url: grpcs://localhost:8051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIIChDCCAiugAwIBAgIQH8HJMhk5uLTy0lTGP5op4DAKBggqhkjOPQQDAjCBjDEL
        MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
        cmFuY2lzY28xJDAiBgNVBAoTG3Jhd21hdGVyaWFsc3VwcGxpZXIuaWJvLmNvbTEq
        MCgGA1UEAxMhdGxzY2EucmF3bWF0ZXJpYWxzdXBwbGllci5pYm8uY29tMB4XDTIw
        MDgyMTIxMDMwMFoXDTMwMDgxOTIxMDMwMFowgYwxCzAJBgNVBAYTAlVTMRMwEQYD
        VQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMSQwIgYDVQQK
        ExtyYXdtYXRlcmlhbHN1cHBsaWVyLmliby5jb20xKjAoBgNVBAMTIXRsc2NhLnJh
        d21hdGVyaWFsc3VwcGxpZXIuaWJvLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEH
        A0IABKa93fRSkr574JwrtQAtZ2ZUyZjeEOat8sBg7U9EoZLkClDtd75Fvki59QDy
        4tHMRi760Gv5iSk1DvMf3mr2/7KjbTBrMA4GA1UdDwEB/wQEAwIBpjAdBgNVHSUE
        FjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zApBgNVHQ4E
        IgQgpBmuOfxTEA3eQZjgLjPFOH6Ef+IWW6/XhoUoyaDSJVMwCgYIKoZIzj0EAwID
        RwAwRAIgOf/81ryza847r1eA8KkcTNL/FakJESOW+498q+zKKWUCIEvmlG2s7H7e
        UqHm+ZK89pMvhmN1Aw0eOdhvs9fsqLP8
        -----END CERTIFICATE-----
        
        
    grpcOptions:
      ssl-target-name-override: peer0.rawmaterialsupplier.ibo.com
      hostnameOverride: peer0.rawmaterialsupplier.ibo.com
  peer1.rawmaterialsupplier.ibo.com:
    url: grpcs://localhost:8055
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIICWDCCAf2gAwIBAgIQMBSnzbHUZjxB05g/51JTqjAKBggqhkjOPQQDAjB2MQsw
        CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
        YW5jaXNjbzEZMBcGA1UEChMQY3VzdG9tZXIuaWJvLmNvbTEfMB0GA1UEAxMWdGxz
        Y2EuY3VzdG9tZXIuaWJvLmNvbTAeFw0yMDA4MjEyMTAzMDBaFw0zMDA4MTkyMTAz
        MDBaMHYxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH
        Ew1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBjdXN0b21lci5pYm8uY29tMR8wHQYD
        VQQDExZ0bHNjYS5jdXN0b21lci5pYm8uY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
        AQcDQgAEVrBifNOob9p6/1YXbx/QkkAUHWyKSeAqokLW1Q01AhzfCgz7vxqWGSjt
        qKdhJgpq/r/BP/4E8tYDEsPeobgoJKNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1Ud
        JQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1Ud
        DgQiBCD92eSomfbjrL5Q5FGKN0w1TMizgpHJD2C4+TYrtpfH/zAKBggqhkjOPQQD
        AgNJADBGAiEAlOc1OtB2hBbXBhNgW9aXX54KhbHuFQmObXgO52c2qi8CIQDE2UMF
        K0715SDBJbWGwNAOQzwVrkFYbDkc8C0e0ps7HQ==
        -----END CERTIFICATE-----
        
    grpcOptions:
      ssl-target-name-override: peer1.rawmaterialsupplier.ibo.com
      hostnameOverride: peer1.rawmaterialsupplier.ibo.com
certificateAuthorities:
  ca.rawmaterialsupplier.ibo.com:
    url: https://localhost:8054
    caName: ca-rawmaterialsupplier
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        MIIChTCCAiygAwIBAgIRAKCFceQFvKAkIi3z+vCK3f0wCgYIKoZIzj0EAwIwgYwx
        CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4g
        RnJhbmNpc2NvMSQwIgYDVQQKExtyYXdtYXRlcmlhbHN1cHBsaWVyLmliby5jb20x
        KjAoBgNVBAMTIXRsc2NhLnJhd21hdGVyaWFsc3VwcGxpZXIuaWJvLmNvbTAeFw0y
        MDA4MjQyMDMzMDBaFw0zMDA4MjIyMDMzMDBaMIGMMQswCQYDVQQGEwJVUzETMBEG
        A1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZyYW5jaXNjbzEkMCIGA1UE
        ChMbcmF3bWF0ZXJpYWxzdXBwbGllci5pYm8uY29tMSowKAYDVQQDEyF0bHNjYS5y
        YXdtYXRlcmlhbHN1cHBsaWVyLmliby5jb20wWTATBgcqhkjOPQIBBggqhkjOPQMB
        BwNCAARAnxI2RZGeILhllVsF+uP9kHbub/C8CbhsHnu4GD0loPf2lbENPzjV4fyR
        d7mrCH2ljGpntK+7r7OVzRy0UbAYo20wazAOBgNVHQ8BAf8EBAMCAaYwHQYDVR0l
        BBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMA8GA1UdEwEB/wQFMAMBAf8wKQYDVR0O
        BCIEIPxyHPdAnk0Io7XFTEbBVpYTBOalarVqIP48LLnqJFP6MAoGCCqGSM49BAMC
        A0cAMEQCIQCOC9fz6N+V7wewVrZ4RyGoRP/dNOLRYZmrJR9TZ9ZYGgIfLaXDcGTz
        brCmVU+gLbeumrpEoGUbSsnJkU//PVkJww==
        -----END CERTIFICATE-----

    httpOptions:
      verify: false
